### ISSUE TITLE
doesn't work in sketch 40.3

### ISSUE THREAD

**Issue by nedzen** [JohnCoates/CSSketch#52]
I downloaded the zip, installed manually and tried to use the example provided. When I change color values in the stylesheet file (sass or less) nothing changes in my .sketch file.

**Comment by ahennie** [comment]
+1

**Comment by himynameisubik** [comment]
Also doesn't work in 41 unfortunately.

**Comment by samueljoos** [comment]
Fixed it and did a pull request but I guess that John Coates is a bit to busy right now.

You can find my fork over here
https://github.com/samueljoos/CSSketch

**Comment by pertrai1** [comment]
@samueljoos I cloned your repo into `Plugins` but when I restarted and tried to install, Sketch shows message that it is already installed. Is there a cache that has Sketch already thinking that it is installed even though I did `rm -rf` on the previous directory before cloning yours?

**Comment by samueljoos** [comment]
You might need to remove the old version from you plugins folder first.

More information to find your plugins folder is here:
http://developer.sketchapp.com/introduction/installing-plugins/

**Comment by AlexanderKozhevin** [comment]
@samueljoos I tried to install yours. But it still doesn't work on 41.1

**Comment by pertrai1** [comment]
@samueljoos Yes I had already removed the old version before cloning yours. I was not able to get it to work with the 41.1

**Comment by caiocall** [comment]
Hi friends. I also tried using this plugin (original version and samueljoos version) and both didn't work. Changes on the CSS files don't do anything on the sketch file. My sketch version is 41.2 (35397). Anyone can help? I'm looking to use it soon! Thanks!

**Comment by caiocall** [comment]
Hi guys, just to let you know, I really wanted to try this plugin so I tested it with other sketch versions below the current version.  With Sketch 3 it will work, if you are interested in just testing it for a while until it's not fixed for newest version but just for experimenting I recommend going to this page and download the older versions: https://www.sketchapp.com/updates/

Hope at least you can see how it works. Hope the owner will update it soon so we can use it with version is 41.2.

**Comment by NSUserDefaults** [comment]
Are there some news about this issue? We need this plugin to work with the latest version.
